### ISSUE TITLE
New feature: Ability to download the visualized ChIA-PET loops 

### ISSUE THREAD

**Issue by martinaryee** [aryeelab/DNAlandscapeR#10]
It would be useful to be able to download the ChIA-PET loops from a specific track in the current view. It would probably be good to include all loops from anchors within the window (even loops where only one anchor is visible). I think a simple tsv/csv table would be best since it would be easy for users to open in Excel and examine (rather than say, an  rda).

**Comment by caleblareau** [comment]
Download option for .tsv as @martinaryee described added in commit 053a6be; working now to implement a more holistic downloader

**Comment by caleblareau** [comment]
Full data download option added in commit 8dbfb22
