### ISSUE TITLE
Inf values in bigwig causes `Error: need finite 'ylim' values`

### ISSUE THREAD

**Issue by martinaryee** [aryeelab/DNAlandscapeR#18]
We could replace Inf with the max non-inf value to get around this.

**Comment by caleblareau** [comment]
@martinaryee What region/track do you see this come up?

**Comment by martinaryee** [comment]
Here's an example: https://dl.dropboxusercontent.com/u/210183/example_with_inf.bw
I looked at chr4:54945264-55314414

**Comment by caleblareau** [comment]
The file that you sent over the region actually has no values in it for that region, but I can reproduce your error message. I'll post a commit that fixes this momentarily

**Comment by caleblareau** [comment]
Fixed in f39de91
