### ISSUE TITLE
The screen greys with "Disconnected from the server" immediately upon connection

### ISSUE THREAD

**Issue by martinaryee** [aryeelab/DNAlandscapeR#22]
<img width="620" alt="screen shot 2016-12-14 at 12 48 42 am" src="https://cloud.githubusercontent.com/assets/1827011/21171120/c2e3aad6-c197-11e6-971c-7645ddffedbf.png">

I think it may have to do with trouble loading the track list from `http://textuploader.com/5buvy/raw`. This page, when loaded into a browser, gives this response before proceeding to the actual file:
![screen shot 2016-12-14 at 12 51 43 am](https://cloud.githubusercontent.com/assets/1827011/21171141/de937856-c197-11e6-8718-04575041b658.png)

Should we move this file to S3?

**Comment by caleblareau** [comment]
Added the source file to here https://raw.githubusercontent.com/aryeelab/dnalandscaper_tracks/master/tracks.txt and pushed a commit; will wait to close until the build (hopefully) succeeds.

**Comment by caleblareau** [comment]
Looks like this was taken care of after moving the summary file elsewhere.
