### ISSUE TITLE
Show anchor width

### ISSUE THREAD

**Issue by martinaryee** [aryeelab/DNAlandscapeR#9]
Suggested feature: Showing the anchor width would help give a sense of the resolution we have.

**Comment by caleblareau** [comment]
Currently, we have two options to display the anchor width...
1) By selecting "Show Single Anchors", the widths of the green section are displayed proportional to the anchor width. Not all anchors in the region will necessarily be displayed.
2) Downloading the table of loops (first option in the Advanced Download panel) and computing them in Excel or some other friendly software for .tsv files.
